/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DB.Ketnoi;
import Home.UserInterface;
import dao.Data;
import dao.LoginRegisterDAO;
import entity.Login;
import entity.LoginRegister;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author hqtru
 */
public class Fr_LoginRegister extends javax.swing.JFrame {

    /**
     * Creates new form Login 
     * Design by Hqtruong
     */
    CardLayout layout;

    public Fr_LoginRegister() {
        initComponents();
//        jPanel1.add("Login", pnlLogin);
        jPanel1.add("Signup", pnlSingup);
        layout = (CardLayout) jPanel1.getLayout();
        setLocationRelativeTo(null);
        pnlOverlay.setBackground(new Color(0,0,0,160));
        pnlOverlay2.setBackground(new Color(0,0,0,160));
        setBackground(new Color(0,0,0,0));
    }

    void jSetColor(JLabel jLabel) {
        jLabel.setForeground(new Color(241, 129, 41));
    }

    void jResetColor(JLabel jLabel) {
        jLabel.setForeground(new Color(204, 204, 204));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblPasswords = new javax.swing.JLabel();
        inputNameSignIn = new javax.swing.JTextField();
        inputPasswords = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        creatone = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNameSignIn = new javax.swing.JLabel();
        pnlButton = new javax.swing.JPanel();
        lblSignin = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        _lableExit = new javax.swing.JLabel();
        rdoDark = new javax.swing.JRadioButton();
        rdoLight = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        pnlOverlay = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlSingup = new javax.swing.JPanel();
        pnlLogin1 = new javax.swing.JPanel();
        lblPasswords1 = new javax.swing.JLabel();
        txtNameSignup = new javax.swing.JTextField();
        txtPassworsd1 = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblNameSignIn1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblNameSignIn2 = new javax.swing.JLabel();
        pnlButton1 = new javax.swing.JPanel();
        lblSignin1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblPasswords2 = new javax.swing.JLabel();
        txtPasswords2 = new javax.swing.JPasswordField();
        lblPasswords4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lblPasswords5 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtEmailSignUp1 = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        pnlExit1 = new javax.swing.JPanel();
        _lableExit1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnlOverlay2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogin.setBackground(new java.awt.Color(45, 46, 48));
        pnlLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLogin.setVerifyInputWhenFocusTarget(false);
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPasswords.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        lblPasswords.setForeground(new java.awt.Color(104, 100, 100));
        lblPasswords.setText("Passwords");
        pnlLogin.add(lblPasswords, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 80, 27));

        inputNameSignIn.setBackground(new java.awt.Color(45, 46, 48));
        inputNameSignIn.setForeground(new java.awt.Color(204, 204, 204));
        inputNameSignIn.setText("Truong");
        inputNameSignIn.setBorder(null);
        inputNameSignIn.setCaretColor(new java.awt.Color(51, 51, 255));
        inputNameSignIn.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        inputNameSignIn.setName(""); // NOI18N
        inputNameSignIn.setVerifyInputWhenFocusTarget(false);
        inputNameSignIn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNameSignInFocusGained(evt);
            }
        });
        pnlLogin.add(inputNameSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 420, 40));

        inputPasswords.setBackground(new java.awt.Color(45, 46, 48));
        inputPasswords.setForeground(new java.awt.Color(204, 204, 204));
        inputPasswords.setText("00000000");
        inputPasswords.setBorder(null);
        inputPasswords.setCaretColor(new java.awt.Color(51, 51, 255));
        inputPasswords.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputPasswordsFocusGained(evt);
            }
        });
        inputPasswords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordsActionPerformed(evt);
            }
        });
        pnlLogin.add(inputPasswords, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 420, 40));

        jSeparator1.setBackground(new java.awt.Color(96, 97, 98));
        jSeparator1.setForeground(new java.awt.Color(96, 97, 98));
        pnlLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 420, 1));

        jSeparator2.setBackground(new java.awt.Color(96, 97, 98));
        jSeparator2.setForeground(new java.awt.Color(96, 97, 98));
        pnlLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 420, 1));

        creatone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        creatone.setForeground(new java.awt.Color(51, 82, 218));
        creatone.setText("Create one !");
        creatone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creatone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creatoneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creatoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creatoneMouseExited(evt);
            }
        });
        pnlLogin.add(creatone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 577, 90, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 122, 122));
        jLabel4.setText("Sign in with:");
        pnlLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 80, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(122, 122, 122));
        jLabel5.setText("Do not have an account ?");
        pnlLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 170, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Google_Plus_32px.png"))); // NOI18N
        pnlLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 40, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Facebook_32px.png"))); // NOI18N
        pnlLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 40, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Twitter_Squared_32px.png"))); // NOI18N
        pnlLogin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 40, 30));

        lblNameSignIn.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        lblNameSignIn.setForeground(new java.awt.Color(5, 140, 196));
        lblNameSignIn.setText("Name");
        pnlLogin.add(lblNameSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 50, 27));

        pnlButton.setBackground(new java.awt.Color(81, 82, 84));

        lblSignin.setBackground(new java.awt.Color(81, 82, 84));
        lblSignin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSignin.setForeground(new java.awt.Color(193, 195, 197));
        lblSignin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignin.setText("Sign in");
        lblSignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSigninMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSigninMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSignin, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSignin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlLogin.add(pnlButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 420, 50));

        pnlExit.setBackground(new java.awt.Color(45, 46, 48));

        _lableExit.setBackground(new java.awt.Color(31, 32, 34));
        _lableExit.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        _lableExit.setForeground(new java.awt.Color(204, 204, 204));
        _lableExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lableExit.setText("X");
        _lableExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _lableExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _lableExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _lableExitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlExitLayout = new javax.swing.GroupLayout(pnlExit);
        pnlExit.setLayout(pnlExitLayout);
        pnlExitLayout.setHorizontalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_lableExit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnlExitLayout.setVerticalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_lableExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlLogin.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 40, 40));

        rdoDark.setBackground(new java.awt.Color(45, 46, 48));
        buttonGroup1.add(rdoDark);
        rdoDark.setForeground(new java.awt.Color(122, 122, 122));
        rdoDark.setText("Dark");
        rdoDark.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdoDarkFocusGained(evt);
            }
        });
        pnlLogin.add(rdoDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, -1, -1));

        rdoLight.setBackground(new java.awt.Color(45, 46, 48));
        buttonGroup1.add(rdoLight);
        rdoLight.setForeground(new java.awt.Color(122, 122, 122));
        rdoLight.setText("Light");
        rdoLight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdoLightFocusGained(evt);
            }
        });
        pnlLogin.add(rdoLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, -1, -1));

        jPanel2.add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 640, 760));

        jPanel3.setLayout(new java.awt.CardLayout());

        pnlOverlay.setBackground(new java.awt.Color(0, 0, 0));
        pnlOverlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/picturetopeople.org-55e8c77d8ff50a6a5e454f8b9a28f26d6d864f7efe20279450.png"))); // NOI18N
        pnlOverlay.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(172, 172, 94));
        jLabel12.setText("Welcome to T1 Mobile Shop");
        pnlOverlay.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 210, 30));

        jPanel3.add(pnlOverlay, "card2");

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 760));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banner/7359b7a100aeccd.jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 760));

        jPanel1.add(jPanel2, "card2");

        pnlSingup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogin1.setBackground(new java.awt.Color(45, 46, 48));
        pnlLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLogin1.setVerifyInputWhenFocusTarget(false);
        pnlLogin1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPasswords1.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        lblPasswords1.setForeground(new java.awt.Color(0, 153, 153));
        lblPasswords1.setText("Passwords");
        pnlLogin1.add(lblPasswords1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 80, 27));

        txtNameSignup.setBackground(new java.awt.Color(45, 46, 48));
        txtNameSignup.setForeground(new java.awt.Color(204, 204, 204));
        txtNameSignup.setBorder(null);
        txtNameSignup.setCaretColor(new java.awt.Color(51, 51, 255));
        txtNameSignup.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtNameSignup.setName(""); // NOI18N
        txtNameSignup.setVerifyInputWhenFocusTarget(false);
        txtNameSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameSignupFocusGained(evt);
            }
        });
        pnlLogin1.add(txtNameSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 420, 30));

        txtPassworsd1.setBackground(new java.awt.Color(45, 46, 48));
        txtPassworsd1.setForeground(new java.awt.Color(204, 204, 204));
        txtPassworsd1.setBorder(null);
        txtPassworsd1.setCaretColor(new java.awt.Color(51, 51, 255));
        txtPassworsd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassworsd1FocusGained(evt);
            }
        });
        txtPassworsd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassworsd1ActionPerformed(evt);
            }
        });
        pnlLogin1.add(txtPassworsd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 420, 30));

        jSeparator3.setBackground(new java.awt.Color(96, 97, 98));
        jSeparator3.setForeground(new java.awt.Color(96, 97, 98));
        pnlLogin1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 420, 1));

        jSeparator4.setBackground(new java.awt.Color(96, 97, 98));
        jSeparator4.setForeground(new java.awt.Color(96, 97, 98));
        pnlLogin1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 420, 1));

        lblNameSignIn1.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        lblNameSignIn1.setForeground(new java.awt.Color(0, 153, 153));
        lblNameSignIn1.setText("Name");
        pnlLogin1.add(lblNameSignIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 50, 27));

        txtAddress.setBackground(new java.awt.Color(45, 46, 48));
        txtAddress.setForeground(new java.awt.Color(204, 204, 204));
        txtAddress.setBorder(null);
        txtAddress.setCaretColor(new java.awt.Color(51, 51, 255));
        txtAddress.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtAddress.setName(""); // NOI18N
        txtAddress.setVerifyInputWhenFocusTarget(false);
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
        });
        pnlLogin1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 420, 30));

        jSeparator5.setBackground(new java.awt.Color(96, 97, 98));
        jSeparator5.setForeground(new java.awt.Color(96, 97, 98));
        pnlLogin1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 420, 1));

        lblNameSignIn2.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        lblNameSignIn2.setForeground(new java.awt.Color(0, 153, 153));
        lblNameSignIn2.setText("Email");
        pnlLogin1.add(lblNameSignIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 50, 27));

        pnlButton1.setBackground(new java.awt.Color(81, 82, 84));

        lblSignin1.setBackground(new java.awt.Color(81, 82, 84));
        lblSignin1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSignin1.setForeground(new java.awt.Color(193, 195, 197));
        lblSignin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignin1.setText("Sign in");
        lblSignin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignin1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSignin1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSignin1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlButton1Layout = new javax.swing.GroupLayout(pnlButton1);
        pnlButton1.setLayout(pnlButton1Layout);
        pnlButton1Layout.setHorizontalGroup(
            pnlButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSignin1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        pnlButton1Layout.setVerticalGroup(
            pnlButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSignin1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlLogin1.add(pnlButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 670, 420, 50));

        jSeparator6.setBackground(new java.awt.Color(96, 97, 98));
        jSeparator6.setForeground(new java.awt.Color(96, 97, 98));
        pnlLogin1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 420, 1));

        lblPasswords2.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        lblPasswords2.setForeground(new java.awt.Color(0, 153, 153));
        lblPasswords2.setText("Accuracy Passwords");
        pnlLogin1.add(lblPasswords2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 27));

        txtPasswords2.setBackground(new java.awt.Color(45, 46, 48));
        txtPasswords2.setForeground(new java.awt.Color(204, 204, 204));
        txtPasswords2.setBorder(null);
        txtPasswords2.setCaretColor(new java.awt.Color(51, 51, 255));
        txtPasswords2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswords2FocusGained(evt);
            }
        });
        txtPasswords2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswords2ActionPerformed(evt);
            }
        });
        pnlLogin1.add(txtPasswords2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 420, 30));

        lblPasswords4.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        lblPasswords4.setForeground(new java.awt.Color(0, 153, 153));
        lblPasswords4.setText("Phone");
        pnlLogin1.add(lblPasswords4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, 27));

        jSeparator7.setBackground(new java.awt.Color(96, 97, 98));
        jSeparator7.setForeground(new java.awt.Color(96, 97, 98));
        pnlLogin1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 420, 1));

        lblPasswords5.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        lblPasswords5.setForeground(new java.awt.Color(0, 153, 153));
        lblPasswords5.setText("Address");
        pnlLogin1.add(lblPasswords5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, 27));

        jSeparator8.setBackground(new java.awt.Color(96, 97, 98));
        jSeparator8.setForeground(new java.awt.Color(96, 97, 98));
        pnlLogin1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 420, 1));

        txtEmailSignUp1.setBackground(new java.awt.Color(45, 46, 48));
        txtEmailSignUp1.setForeground(new java.awt.Color(204, 204, 204));
        txtEmailSignUp1.setBorder(null);
        txtEmailSignUp1.setCaretColor(new java.awt.Color(51, 51, 255));
        txtEmailSignUp1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtEmailSignUp1.setName(""); // NOI18N
        txtEmailSignUp1.setVerifyInputWhenFocusTarget(false);
        txtEmailSignUp1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailSignUp1FocusGained(evt);
            }
        });
        pnlLogin1.add(txtEmailSignUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 420, 30));

        txtPhone.setBackground(new java.awt.Color(45, 46, 48));
        txtPhone.setForeground(new java.awt.Color(204, 204, 204));
        txtPhone.setBorder(null);
        txtPhone.setCaretColor(new java.awt.Color(51, 51, 255));
        txtPhone.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtPhone.setName(""); // NOI18N
        txtPhone.setVerifyInputWhenFocusTarget(false);
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
        });
        pnlLogin1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 420, 30));

        pnlSingup.add(pnlLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 760));

        pnlExit1.setBackground(new java.awt.Color(45, 46, 48));

        _lableExit1.setBackground(new java.awt.Color(31, 32, 34));
        _lableExit1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        _lableExit1.setForeground(new java.awt.Color(204, 204, 204));
        _lableExit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lableExit1.setText("X");
        _lableExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _lableExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _lableExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _lableExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _lableExit1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlExit1Layout = new javax.swing.GroupLayout(pnlExit1);
        pnlExit1.setLayout(pnlExit1Layout);
        pnlExit1Layout.setHorizontalGroup(
            pnlExit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_lableExit1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnlExit1Layout.setVerticalGroup(
            pnlExit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_lableExit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSingup.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, -1));

        jPanel4.setLayout(new java.awt.CardLayout());

        pnlOverlay2.setBackground(new java.awt.Color(0, 0, 0));
        pnlOverlay2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/picturetopeople.org-55e8c77d8ff50a6a5e454f8b9a28f26d6d864f7efe20279450.png"))); // NOI18N
        pnlOverlay2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(172, 172, 94));
        jLabel17.setText("Welcome to T1 Mobile Shop");
        pnlOverlay2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 210, 30));

        jPanel4.add(pnlOverlay2, "card2");

        pnlSingup.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 640, 760));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banner/7359b7a100aeccd.jpg"))); // NOI18N
        pnlSingup.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 640, 760));

        jPanel1.add(pnlSingup, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoLightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdoLightFocusGained
        // TODO add your handling code here:
        pnlLogin.setBackground(new Color(236, 236, 236));
        rdoDark.setBackground(new Color(236, 236, 236));
        rdoLight.setBackground(new Color(236, 236, 236));
        inputNameSignIn.setBackground(new Color(236, 236, 236));
        inputPasswords.setBackground(new Color(236, 236, 236));
        pnlButton.setBackground(new Color(209, 209, 209));
        pnlExit.setBackground(new Color(214, 212, 215));
        _lableExit.setForeground(new Color(81, 82, 84));
        lblSignin.setForeground(new Color(12, 22, 22));
    }//GEN-LAST:event_rdoLightFocusGained

    private void rdoDarkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdoDarkFocusGained
        // TODO add your handling code here:
        pnlLogin.setBackground(new Color(45, 46, 48));
        rdoDark.setBackground(new Color(45, 46, 48));
        rdoLight.setBackground(new Color(45, 46, 48));
        inputNameSignIn.setBackground(new Color(45, 46, 48));
        inputPasswords.setBackground(new Color(45, 46, 48));
        pnlButton.setBackground(new Color(81, 82, 84));
        pnlExit.setBackground(new Color(45, 46, 48));
        _lableExit.setForeground(new Color(204, 204, 204));
        lblSignin.setForeground(new Color(193, 195, 197));
    }//GEN-LAST:event_rdoDarkFocusGained

    private void _lableExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lableExitMousePressed
        // TODO add your handling code here:
        float f = 0;
        for (double i = 1.0; i > 0.0; i = i - 0.1) {
            f = (float) i;
            this.setOpacity(f);
            try {
                Thread.sleep(15);
            } catch (Exception ex) {

            }
        }
        System.exit(0);
    }//GEN-LAST:event__lableExitMousePressed

    private void _lableExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lableExitMouseExited
        // TODO add your handling code here:

        if (rdoLight.isSelected()) {
            pnlExit.setBackground(new Color(236, 236, 236));
            _lableExit.setForeground(new Color(45, 46, 48));
        } else {
            pnlExit.setBackground(new Color(45, 46, 48));
            _lableExit.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event__lableExitMouseExited

    private void _lableExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lableExitMouseEntered
        // TODO add your handling code here:
        if (rdoDark.isSelected()) {
            pnlExit.setBackground(new Color(81, 82, 84));
            _lableExit.setForeground(new Color(214, 212, 215));
        } else {
            pnlExit.setBackground(new Color(81, 82, 84));
            _lableExit.setForeground(new Color(214, 212, 215));
        }
    }//GEN-LAST:event__lableExitMouseEntered

    private void lblSigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSigninMouseExited
        // TODO add your handling code here:
        if (rdoLight.isSelected()) {
            pnlButton.setBackground(new Color(209, 209, 209));
            lblSignin.setForeground(new Color(12, 22, 22));
        } else {
            pnlButton.setBackground(new Color(81, 82, 84));
            lblSignin.setForeground(new Color(193, 195, 197));
        }
    }//GEN-LAST:event_lblSigninMouseExited

    private void lblSigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSigninMouseEntered
        // TODO add your handling code here:
        if (rdoLight.isSelected()) {
            pnlButton.setBackground(new Color(144, 143, 149));
        } else {
            pnlButton.setBackground(new Color(101, 103, 104));
        }
    }//GEN-LAST:event_lblSigninMouseEntered

    private void inputPasswordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordsActionPerformed

    private void inputPasswordsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPasswordsFocusGained
        // TODO add your handling code here:
        lblNameSignIn.setForeground(new Color(104, 100, 100));
        lblPasswords.setForeground(new Color(5, 140, 196));
        jSeparator2.setForeground(new Color(150, 150, 150));
        jSeparator1.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_inputPasswordsFocusGained

    private void inputNameSignInFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNameSignInFocusGained
        // TODO add your handling code here:
        lblNameSignIn.setForeground(new Color(5, 140, 196));
        lblPasswords.setForeground(new Color(104, 100, 100));
        jSeparator1.setForeground(new Color(150, 150, 150));
        jSeparator2.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_inputNameSignInFocusGained

    private void lblSigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSigninMouseClicked
        // TODO add your handling code here:
        String groupname = null;
        String name = inputNameSignIn.getText();
        char[] pwd = inputPasswords.getPassword();
        String pass = String.copyValueOf(pwd);
        AdminInterface mAdmin = new AdminInterface();
        UserInterface user = new UserInterface();
        String err = "";
        if (name.length() == 0 && pwd.length == 0) {
            err += "Vui lòng điền tài khoản và mật khẩu!";
        } else if (name.length() == 0 || pwd.length == 0) {
            if (name.length() == 0) {
                err += "Tài khoản không được để trống";
            } else if (pwd.length == 0) {
                err += "Mật khẩu không được để trống";
            }
        } else {
            List<Login> LG = new ArrayList<>();
            Connection con;
            CallableStatement ca = null;
            ResultSet rs = null;
            con = Ketnoi.open();
            try {
                ca = con.prepareCall("{ call LoginUser }");
                rs = ca.executeQuery();
                while (rs.next()) {
                    Login login = new Login();
                    login.setId(rs.getInt("id"));
                    login.setName(rs.getString("name"));
                    login.setPassword(rs.getString("password"));
                    login.setGroup_name(rs.getBoolean("group_name"));
                    LG.add(login);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Fr_LoginRegister.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                Ketnoi.closeAll(con, ca, rs);
            }

//            boolean bl = false;
            String check = "";
           
            for (Login lg : LG) {
                if (name.equals(lg.getName()) && pass.equals(lg.getPassword())) {
                    if (lg.isGroup_name() == true) {
                        mAdmin.xinChao(lg.getName());
                        check = "ok";
                        Data.setId(lg.getId());
                    } else {
                        user.xinChao(lg.getName());
                        check = "notok";   
                        Data.setId(lg.getId());
                    }
                }
            }
            if (check.equals("ok")) {
                JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công");
                mAdmin.setVisible(true);
                mAdmin.setEnabled(true);
                dispose();
            } else if (check.equals("notok")) {
                JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công");
                user.setVisible(true);
                dispose();
            } else {
                err += "Thông tin tài khoản hoặc mật khẩu không chính xác";
            }

        }
        if (err.length() != 0) {
            JOptionPane.showMessageDialog(rootPane, err, "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblSigninMouseClicked

    private void creatoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatoneMouseClicked
        float f = 0;
        for (double i = 0.0; i < 1.0; i = i + 0.1) {
            f = (float) i;
            this.setOpacity(f);
            try {
                Thread.sleep(15);
                layout.show(jPanel1, "Signup");
            } catch (Exception ex) {

            }
        }
    }//GEN-LAST:event_creatoneMouseClicked

    private void creatoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatoneMouseEntered
        creatone.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_creatoneMouseEntered

    private void creatoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatoneMouseExited
        creatone.setForeground(new Color(51, 82, 218));
    }//GEN-LAST:event_creatoneMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i < 1.0; i = i + 0.1) {
            float f = (float) i;
            this.setOpacity(f);
            try {
                Thread.sleep(15);
            } catch (InterruptedException ex) {
                Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened
    int xx, xy;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void txtNameSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameSignupFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameSignupFocusGained

    private void txtPassworsd1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassworsd1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassworsd1FocusGained

    private void txtPassworsd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassworsd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassworsd1ActionPerformed

    private void lblSignin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignin1MouseClicked
        String name = txtNameSignup.getText();
        String email = txtAddress.getText();
        String passwords1 = new String(txtPassworsd1.getPassword());
        String passwords2 = new String(txtPasswords2.getPassword());
        String phone = txtPhone.getText();
        String address = txtAddress.getText();
        
        String err = "";
        
        if(name.length()==0)
            err += "\n- Don't leave empty your name login.";
        if(email.length()==0)
            err += "\n- Don't leave empty your email.";
        if(passwords1.length()==0)
            err += "\n- Don't leave empty your passwords.";
        if(passwords2.length()==0){
         err += "\n- Don't leave empty accuracy passwords.";
        }else{
         if(!passwords1.equals(passwords2))
             err ="\n- Accucary passwords not like your passwords.";
            }
        if(phone.length()==0){
            err += "\n- Don't leave empty phone.";
        }
        if(address.length()==0){
            err += "\n- Don't leave empty address.";
        }
        if(err.length()==0){
            LoginRegister lr = new LoginRegister(0, name, email, passwords2, phone, address);
            boolean blInsert = new LoginRegisterDAO().insertLoginRegister(lr);
            if(blInsert)
                JOptionPane.showMessageDialog(this, "Register Success !");
            Fr_LoginRegister f = new Fr_LoginRegister();
            f.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, err);
           
        }
    }//GEN-LAST:event_lblSignin1MouseClicked

    private void lblSignin1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignin1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSignin1MouseEntered

    private void lblSignin1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignin1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSignin1MouseExited

    private void _lableExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lableExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event__lableExit1MouseEntered

    private void _lableExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lableExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event__lableExit1MouseExited

    private void _lableExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lableExit1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event__lableExit1MousePressed

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtPasswords2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswords2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswords2FocusGained

    private void txtPasswords2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswords2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswords2ActionPerformed

    private void _lableExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lableExit1MouseClicked
        float f = 0;
        for (double i = 1.0; i > 0.0; i = i - 0.1) {
            f = (float) i;
            this.setOpacity(f);
            try {
                Thread.sleep(15);
            } catch (Exception ex) {

            }
        }
        System.exit(0);
    }//GEN-LAST:event__lableExit1MouseClicked

    private void txtEmailSignUp1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailSignUp1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailSignUp1FocusGained

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fr_LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fr_LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fr_LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fr_LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fr_LoginRegister().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lableExit;
    private javax.swing.JLabel _lableExit1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel creatone;
    private javax.swing.JTextField inputNameSignIn;
    private javax.swing.JPasswordField inputPasswords;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblNameSignIn;
    private javax.swing.JLabel lblNameSignIn1;
    private javax.swing.JLabel lblNameSignIn2;
    private javax.swing.JLabel lblPasswords;
    private javax.swing.JLabel lblPasswords1;
    private javax.swing.JLabel lblPasswords2;
    private javax.swing.JLabel lblPasswords4;
    private javax.swing.JLabel lblPasswords5;
    private javax.swing.JLabel lblSignin;
    private javax.swing.JLabel lblSignin1;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlButton1;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlExit1;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLogin1;
    private javax.swing.JPanel pnlOverlay;
    private javax.swing.JPanel pnlOverlay2;
    private javax.swing.JPanel pnlSingup;
    private javax.swing.JRadioButton rdoDark;
    private javax.swing.JRadioButton rdoLight;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmailSignUp1;
    private javax.swing.JTextField txtNameSignup;
    private javax.swing.JPasswordField txtPasswords2;
    private javax.swing.JPasswordField txtPassworsd1;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

}
