/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import dao.Data;
import dao.orderDAO;
import entity.CartProduct;
import entity.Order;
import entity.orderDetail;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hqtru
 */
public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    DefaultTableModel defaultTableModel, defaultTableModel1;
    CardLayout layout;
    List<CartProduct> ListCartProducts;

    public List<CartProduct> getListCartProducts() {
        return ListCartProducts;
    }

    public void setListCartProducts(List<CartProduct> ListCartProducts) {
        this.ListCartProducts = ListCartProducts;
    }

    public Cart() {
        initComponents();
        defaultTableModel = new DefaultTableModel();
        String[] _tblCart = {"id", "Tên sản phẩm", "Số lượng","Giá", "Tổng Giá", "Bảo hành", "Tình Trạng"};
        defaultTableModel.setColumnIdentifiers(_tblCart);
        tblCart.setModel(defaultTableModel);
        String[] _tblOrder = {"id", "Tên sản phẩm", "Số lượng","Giá", "Tổng Giá", "Bảo hành", "Tình Trạng"};
        defaultTableModel1 = new DefaultTableModel(_tblOrder, 0);
        tblOrder.setModel(defaultTableModel1);
        _pnlPanel.add("_Order", pnlOrder);
        layout = (CardLayout) _pnlPanel.getLayout();
        loadDataProduct();
        setLocationRelativeTo(null);
    }
    public List<CartProduct> cart;

    public void loadDataProduct() {
        cart = ProductDetail.c;
        defaultTableModel.setRowCount(0);
        for (CartProduct haha : cart) {
             double Totalprice = haha.getPriceProduct()*haha.getQuantity();
            Object ob[] = {haha.getId(), haha.getNameProduct(), haha.getQuantity(), haha.getPriceProduct(),Totalprice, haha.getBaoHanh(), haha.isTinhTrang()};
            defaultTableModel.addRow(ob);
            defaultTableModel1.addRow(ob);
        }
    }

    public void fillData() {
        loadDataProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _pnlPanel = new javax.swing.JPanel();
        pnlCart = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        lblDelete12 = new javax.swing.JLabel();
        kBtnDelete = new keeptoo.KButton();
        lblUpdate = new javax.swing.JLabel();
        kButton2 = new keeptoo.KButton();
        lblAddnew = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        pnlOrder = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        lblUpdate1 = new javax.swing.JLabel();
        kButton3 = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblExit1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _pnlPanel.setLayout(new java.awt.CardLayout());

        pnlCart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(217, 214, 214));
        kGradientPanel1.setkFillBackground(false);
        kGradientPanel1.setkStartColor(new java.awt.Color(217, 214, 214));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        tblCart.setAutoCreateRowSorter(true);
        tblCart.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, "", null, ""},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Giá", "Khuyến mãi", "Bảo Hành", "Tình Trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCart.setGridColor(new java.awt.Color(255, 255, 255));
        tblCart.setRowHeight(30);
        tblCart.setRowMargin(4);
        tblCart.setSelectionBackground(new java.awt.Color(32, 62, 102));
        tblCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCart);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 950, 260));

        lblDelete12.setBackground(new java.awt.Color(51, 51, 51));
        lblDelete12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDelete12.setForeground(new java.awt.Color(255, 255, 255));
        lblDelete12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDelete12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Trash_Can_21px.png"))); // NOI18N
        lblDelete12.setText("Delete");
        lblDelete12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDelete12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDelete12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDelete12MouseExited(evt);
            }
        });
        kGradientPanel1.add(lblDelete12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, 40));

        kBtnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kBtnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kBtnDelete.setIconTextGap(5);
        kBtnDelete.setkAllowTab(false);
        kBtnDelete.setkBorderRadius(0);
        kBtnDelete.setkEndColor(new java.awt.Color(240, 240, 240));
        kBtnDelete.setkHoverEndColor(new java.awt.Color(111, 163, 244));
        kBtnDelete.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kBtnDelete.setkHoverStartColor(new java.awt.Color(111, 163, 244));
        kBtnDelete.setkStartColor(new java.awt.Color(131, 79, 28));
        kBtnDelete.setMargin(new java.awt.Insets(21, 141, 21, 141));
        kBtnDelete.setMultiClickThreshhold(52L);
        kBtnDelete.setOpaque(false);
        kBtnDelete.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        kBtnDelete.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        kGradientPanel1.add(kBtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, 40));

        lblUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Purchase_Order_21px_1.png"))); // NOI18N
        lblUpdate.setText("Đặt Hàng");
        lblUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUpdateMouseExited(evt);
            }
        });
        kGradientPanel1.add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 130, 40));

        kButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kButton2.setkAllowTab(false);
        kButton2.setkBorderRadius(0);
        kButton2.setkEndColor(new java.awt.Color(241, 255, 255));
        kButton2.setkHoverEndColor(new java.awt.Color(111, 163, 244));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(111, 163, 244));
        kButton2.setkIndicatorThickness(100);
        kButton2.setkStartColor(new java.awt.Color(132, 152, 112));
        kButton2.setMargin(new java.awt.Insets(21, 141, 21, 141));
        kButton2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        kButton2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 130, 40));

        lblAddnew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddnew.setForeground(new java.awt.Color(255, 255, 255));
        lblAddnew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Restart_24px.png"))); // NOI18N
        lblAddnew.setText("Sửa Số Lượng");
        lblAddnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddnewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddnewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddnewMouseExited(evt);
            }
        });
        kGradientPanel1.add(lblAddnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 140, 40));

        kButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kButton1.setkAllowTab(false);
        kButton1.setkBorderRadius(0);
        kButton1.setkEndColor(new java.awt.Color(40, 117, 239));
        kButton1.setkHoverEndColor(new java.awt.Color(111, 163, 244));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(111, 163, 244));
        kButton1.setkStartColor(new java.awt.Color(40, 117, 239));
        kButton1.setMargin(new java.awt.Insets(21, 141, 21, 141));
        kButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        kButton1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 140, 40));

        pnlCart.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 1060, 500));

        jPanel2.setBackground(new java.awt.Color(50, 30, 89));
        jPanel2.setPreferredSize(new java.awt.Dimension(60, 680));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Male_User_40px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Talk_22px.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 40, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Home_22px.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Google_News_22px_1.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, 40));

        pnlCart.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 680));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 42)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Shopping_Cart_100px.png"))); // NOI18N
        jLabel14.setText("Cart");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 320, 80));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banner/logo-iphone-1-1494420922380.png"))); // NOI18N
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 250, 100));

        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Cancel_32px.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel7.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 50, 50));

        pnlCart.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 1120, 110));

        _pnlPanel.add(pnlCart, "card2");

        pnlOrder.setMaximumSize(new java.awt.Dimension(1180, 700));
        pnlOrder.setMinimumSize(new java.awt.Dimension(1180, 700));
        pnlOrder.setPreferredSize(new java.awt.Dimension(1180, 700));
        pnlOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(217, 214, 214));
        kGradientPanel2.setkFillBackground(false);
        kGradientPanel2.setkStartColor(new java.awt.Color(217, 214, 214));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUpdate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUpdate1.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Purchase_Order_21px_1.png"))); // NOI18N
        lblUpdate1.setText("Thanh Toán");
        lblUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdate1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUpdate1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUpdate1MouseExited(evt);
            }
        });
        kGradientPanel2.add(lblUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, 140, 40));

        kButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kButton3.setkAllowTab(false);
        kButton3.setkBorderRadius(0);
        kButton3.setkEndColor(new java.awt.Color(241, 255, 255));
        kButton3.setkHoverEndColor(new java.awt.Color(111, 163, 244));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(111, 163, 244));
        kButton3.setkIndicatorThickness(100);
        kButton3.setkStartColor(new java.awt.Color(132, 152, 112));
        kButton3.setMargin(new java.awt.Insets(21, 141, 21, 141));
        kButton3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        kButton3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        kGradientPanel2.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, 140, 40));

        jLabel1.setText("Email:");
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 70, 30));

        jLabel2.setText("Họ Tên");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 70, 30));

        jLabel3.setText("Điện Thoại");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 70, 30));
        kGradientPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 330, 30));
        kGradientPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 330, 30));
        kGradientPanel2.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 330, 30));

        jLabel4.setText("Địa Chỉ:");
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 70, 30));

        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("(*)");
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 20, 30));

        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("(*)");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 20, 30));

        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("(*)");
        kGradientPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 20, 30));

        jLabel19.setForeground(new java.awt.Color(255, 51, 0));
        jLabel19.setText("(*)");
        kGradientPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 160, 20, 30));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.setBorder(null);
        jScrollPane3.setViewportView(txtAddress);

        kGradientPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 330, 120));

        jScrollPane4.setBorder(null);

        tblOrder.setAutoCreateRowSorter(true);
        tblOrder.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, "", null, ""},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Giá", "Khuyến mãi", "Bảo Hành", "Tình Trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrder.setGridColor(new java.awt.Color(255, 255, 255));
        tblOrder.setRowHeight(30);
        tblOrder.setRowMargin(4);
        tblOrder.setSelectionBackground(new java.awt.Color(32, 62, 102));
        jScrollPane4.setViewportView(tblOrder);

        kGradientPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 550, 320));

        pnlOrder.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 1060, 540));

        jPanel3.setBackground(new java.awt.Color(50, 30, 89));
        jPanel3.setPreferredSize(new java.awt.Dimension(60, 700));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Male_User_40px.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Talk_22px.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 40, 40));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Home_22px.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, 40));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Google_News_22px_1.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, 40));

        pnlOrder.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 680));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 42)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Mobile_Order_100px.png"))); // NOI18N
        jLabel18.setText("Order");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 320, 80));

        lblExit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Cancel_32px.png"))); // NOI18N
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExit1MouseExited(evt);
            }
        });
        jPanel8.add(lblExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 50, 50));

        pnlOrder.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 1120, 80));

        _pnlPanel.add(pnlOrder, "card3");

        getContentPane().add(_pnlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered

    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited

    }//GEN-LAST:event_lblExitMouseExited

    private void lblDelete12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelete12MouseEntered
        lblDelete12.setOpaque(true);
        lblDelete12.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblDelete12MouseEntered

    private void lblDelete12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelete12MouseExited
        lblDelete12.setOpaque(false);
        lblDelete12.setBackground(Color.red);
    }//GEN-LAST:event_lblDelete12MouseExited

    private void lblUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseClicked
        Cart cart1 = new Cart();
        cart1.loadDataProduct();
        layout.show(_pnlPanel, "_Order");

    }//GEN-LAST:event_lblUpdateMouseClicked

    private void lblUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseEntered
        lblUpdate.setOpaque(true);
        lblUpdate.setBackground(new Color(132, 152, 112));
    }//GEN-LAST:event_lblUpdateMouseEntered

    private void lblUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseExited
        lblUpdate.setOpaque(false);
        lblUpdate.setBackground(new Color(232, 152, 112));
    }//GEN-LAST:event_lblUpdateMouseExited

    private void lblAddnewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddnewMouseClicked
        int row = tblCart.getSelectedRow();
        int sl = cart.get(row).getQuantity();
        String show = JOptionPane.showInputDialog(this, "Mời bạn nhập", sl);
        try {
           int n = Integer.parseInt(show);
                 if (n > 0) {
                     tblCart.setValueAt(n, row, 2);
                 }else
         JOptionPane.showMessageDialog(this, "Không là số âm");
        } catch (Exception e) {
            if ( show != null) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng");
            }
        }
        
    }//GEN-LAST:event_lblAddnewMouseClicked

    private void lblAddnewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddnewMouseEntered
        lblAddnew.setOpaque(true);
        lblAddnew.setBackground(new Color(232, 152, 112));
    }//GEN-LAST:event_lblAddnewMouseEntered

    private void lblAddnewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddnewMouseExited
        lblAddnew.setOpaque(false);
        lblAddnew.setBackground(new Color(132, 152, 112));
    }//GEN-LAST:event_lblAddnewMouseExited

    private void lblDelete12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelete12MouseClicked
        int row = tblCart.getSelectedRow();
        cart.remove(row);
        defaultTableModel.removeRow(row);
    }//GEN-LAST:event_lblDelete12MouseClicked

    private void lblUpdate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdate1MouseClicked
        Order od = new Order();
        od.setOrderDate(new Date());
        od.setNameUser(txtName.getText());
        od.setEmail(txtEmail.getText());
        od.setPhone(Integer.parseInt(txtPhone.getText()));
        od.setAddress(txtAddress.getText());
        boolean inserts = new orderDAO().inserts(od, Data.getId());

        if (inserts) {
            boolean bl = false;
            int maDathang = new orderDAO().getmaDathang();
            orderDAO orderDAO = new orderDAO();

            for (CartProduct sp : cart) {
                orderDetail odt = new orderDetail();
                odt.setProductName(sp.getNameProduct());
                odt.setPrice(sp.getPriceProduct());
                odt.setOrderId(maDathang);
                odt.setQty(sp.getQuantity());
                boolean insertOrderDetail = orderDAO.insertOrderDetail(odt);
                if (!insertOrderDetail) {
                    bl = false;
                }
                if (insertOrderDetail) {
                    JOptionPane.showMessageDialog(rootPane, "Đặt hàng thành công");
                    UserInterface u = new UserInterface();
                    u.setVisible(true);
                    u.setlocationMyOrder();
                    u.myOrder();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Lỗi ");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Có lỗi khi đặt hàng");
        }
    }//GEN-LAST:event_lblUpdate1MouseClicked

    private void lblUpdate1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdate1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUpdate1MouseEntered

    private void lblUpdate1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdate1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUpdate1MouseExited

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExit1MouseClicked

    private void lblExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExit1MouseEntered

    private void lblExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseExited

    }//GEN-LAST:event_lblExit1MouseExited

    UserInterface user = new UserInterface();
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        user = new UserInterface();
        user.setVisible(true);
        user.setlocation();
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        user = new UserInterface();
        user.setVisible(true);
        user.setlocationNews();
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        user = new UserInterface();
        user.setVisible(true);
        user.setlocationFeedback();
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        user = new UserInterface();
        user.setVisible(true);
        user.setlocation();
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        user = new UserInterface();
        user.setVisible(true);
        user.setlocationNews();
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        user = new UserInterface();
        user.setVisible(true);
        user.setlocationFeedback();
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void tblCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCartMouseClicked
       int row = tblCart.getSelectedRow();
       Object[] dl = {defaultTableModel.getValueAt(row, 0),defaultTableModel.getValueAt(row, 1),defaultTableModel.getValueAt(row, 2),
       defaultTableModel.getValueAt(row, 3),defaultTableModel.getValueAt(row, 4),defaultTableModel.getValueAt(row, 5)};
       
    }//GEN-LAST:event_tblCartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _pnlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private keeptoo.KButton kBtnDelete;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblAddnew;
    private javax.swing.JLabel lblDelete12;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblUpdate1;
    private javax.swing.JPanel pnlCart;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
