/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import dao.productDAO;
import entity.CartProduct;
import entity.product;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hqtru
 */
public class ProductDetail extends javax.swing.JFrame {

    /**
     * Creates new form ProductDetail
     */
    public ProductDetail() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void viewData() {
        List<product> p = new productDAO().GetAllCategory();
        int id = Integer.parseInt(UserInterface.id);
        product pr = productDAO.getCategorybyId(id);
        lblIdDetail.setText(String.valueOf(id));
        lblNameProduct.setText(String.valueOf(pr.getName()));
        lblPriceProduct1.setText(String.valueOf(pr.getPrice()));
        lblBaohanh.setText(pr.getGuarantee());
        lblPriceProduct.setText(String.valueOf(pr.getPrice() - pr.getSalePrice()));
        lblsalePriceProduct.setText(String.valueOf((pr.getSalePrice() / pr.getPrice()) * 100) + " %");
        txtQuantityProduct.setText("1");
        ImageIcon icon = new ImageIcon(pr.getImages());
        lblImagesProduct.setIcon(icon);
        String h;
        if (pr.isStatus() == true) {
            h = "100%";
        } else {
            h = "99%";
        }
        lblTinhTrang.setText(h);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImagesProduct = new javax.swing.JLabel();
        lblNameProduct = new javax.swing.JLabel();
        lblsalePriceProduct = new javax.swing.JLabel();
        txtQuantityProduct = new javax.swing.JTextField();
        lblPriceProduct = new javax.swing.JLabel();
        kbtnDatHang = new keeptoo.KButton();
        lblBaohanh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblPriceProduct1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTinhTrang = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblsalePriceProduct1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblImagesProduct1 = new javax.swing.JLabel();
        lblNameProduct1 = new javax.swing.JLabel();
        txtQuantityProduct1 = new javax.swing.JTextField();
        lblPriceProduct2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblIdDetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(50, 30, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Male_User_40px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Talk_22px.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 40, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Home_22px.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Google_News_22px_1.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 720));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(1140, 110));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 42)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Product Detail");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 390, 80));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cb9407f390e70e8a6eedcf71b0ebb4cd - Copy.png"))); // NOI18N
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 290, 110));

        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestIcon/icons8_Cancel_32px.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel7.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 50, 50));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 1140, 110));

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(232, 232, 232));
        kGradientPanel1.setkFillBackground(false);
        kGradientPanel1.setkStartColor(new java.awt.Color(232, 232, 232));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(355, 420));

        lblImagesProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagesProduct.setPreferredSize(new java.awt.Dimension(350, 400));
        jScrollPane1.setViewportView(lblImagesProduct);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 420));

        lblNameProduct.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        kGradientPanel1.add(lblNameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 390, 40));
        kGradientPanel1.add(lblsalePriceProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 110, 30));

        txtQuantityProduct.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtQuantityProduct.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(txtQuantityProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 50, 40));

        lblPriceProduct.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        kGradientPanel1.add(lblPriceProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 330, 30));

        kbtnDatHang.setText("Đặt Hàng");
        kbtnDatHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kbtnDatHang.setkBorderRadius(0);
        kbtnDatHang.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        kbtnDatHang.setkHoverStartColor(new java.awt.Color(0, 255, 0));
        kbtnDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtnDatHangActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kbtnDatHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 330, -1));
        kGradientPanel1.add(lblBaohanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 130, 30));

        jLabel1.setText("Tiết kiệm: ");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 70, 30));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        kGradientPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 155, 90, 1));

        lblPriceProduct1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblPriceProduct1.setForeground(new java.awt.Color(102, 102, 102));
        kGradientPanel1.add(lblPriceProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 110, 30));

        jLabel7.setText("Tình Trạng:");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 70, 30));
        kGradientPanel1.add(lblTinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 80, 30));

        jLabel12.setText("Quantity");
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 50, 40));
        kGradientPanel1.add(lblsalePriceProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 110, 30));

        lblImagesProduct1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagesProduct1.setText("Images Product");
        jScrollPane2.setViewportView(lblImagesProduct1);

        kGradientPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 355, 420));

        lblNameProduct1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        kGradientPanel1.add(lblNameProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 390, 40));
        kGradientPanel1.add(txtQuantityProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 50, 40));

        lblPriceProduct2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        kGradientPanel1.add(lblPriceProduct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 330, 30));

        jLabel13.setText("Bảo Hành");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 70, 30));

        lblIdDetail.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(lblIdDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(941, 20, 80, 30));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 1050, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered

    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited

    }//GEN-LAST:event_lblExitMouseExited
    public static List<CartProduct> c = new ArrayList<>();
    private void kbtnDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtnDatHangActionPerformed
        String id = lblIdDetail.getText();
        String quantity = txtQuantityProduct.getText();
        String name = lblNameProduct.getText();
        Float price = Float.parseFloat(lblPriceProduct1.getText());
        String baoHanh = lblBaohanh.getText();
        boolean bll = Boolean.parseBoolean(lblTinhTrang.getText());
        int _id = Integer.parseInt(id);
        int qty = 0;
        try {
            qty = Integer.parseInt(quantity);
            if (qty <= 0) {
                txtQuantityProduct.setText("1");
                JOptionPane.showMessageDialog(this, "Phải là số dương");
                return;
            }
        } catch (NumberFormatException e) {
            txtQuantityProduct.setText("1");
            JOptionPane.showMessageDialog(this, "Không là kí tự");
            return;
        }
        if (c.size() == 0) {
            CartProduct cartProduct = new CartProduct(_id, name, price, qty, baoHanh, bll);
            c.add(cartProduct);
        } else {
            boolean bl = false;
            for (int i = 0; i < c.size(); i++) {
                if (_id == c.get(i).getId()) {
                    int qt1 = c.get(i).getQuantity() + qty;
                    CartProduct cartProduct = new CartProduct(_id, name, price, qt1, baoHanh, bl);
                    bl = true;
                    c.set(i, cartProduct);
                }
            }
            if (!bl) {
                CartProduct cartProduct = new CartProduct(_id, name, price, qty, baoHanh, bl);
                c.add(cartProduct);
            }
        }
        Cart cart = new Cart();
        cart.setVisible(true);
        dispose();
    }//GEN-LAST:event_kbtnDatHangActionPerformed

    UserInterface user = new UserInterface();
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        user.setVisible(true);
        user.setlocation();
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        user = new UserInterface();
        user.setVisible(true);
        user.setlocationNews();
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        user = new UserInterface();
        user.setVisible(true);
        user.setlocationFeedback();
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KButton kbtnDatHang;
    private javax.swing.JLabel lblBaohanh;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblIdDetail;
    private javax.swing.JLabel lblImagesProduct;
    private javax.swing.JLabel lblImagesProduct1;
    private javax.swing.JLabel lblNameProduct;
    private javax.swing.JLabel lblNameProduct1;
    private javax.swing.JLabel lblPriceProduct;
    private javax.swing.JLabel lblPriceProduct1;
    private javax.swing.JLabel lblPriceProduct2;
    private javax.swing.JLabel lblTinhTrang;
    private javax.swing.JLabel lblsalePriceProduct;
    private javax.swing.JLabel lblsalePriceProduct1;
    private javax.swing.JTextField txtQuantityProduct;
    private javax.swing.JTextField txtQuantityProduct1;
    // End of variables declaration//GEN-END:variables
}
